### ISSUE TITLE
Shotgun is over powered

### ISSUE THREAD

**Issue by Tripperful** [Tripperful/sf-servers-requests#3]
## Shotgun Damage Changes
The damage changes with the shotgun to make it more consistent resulted in a 23% buff to the shotgun. While the consistency of the weapon is nice it feels a bit over powered at this point.

### Possible Fixes
- Give the shotgun a wider cone / spray
- Give a variable to allow shotgun damage per pellet adjustments

**Comment by Tripperful** [comment]
I think a bigger spread cone is the first thing worth trying, shotgun should be very powerful in close range but should lose its strength VERY quickly with distance. This is not what is happening now, people get -100hp’ed from 10 meters away

**Comment by wburwell** [comment]
If this is not possible we should at least experiment with damage numbers and the tracehull variable to find a happy medium.

**Comment by da11as911** [comment]
If this ends up not being possible to reduce by range, then I suggest we at least look at experimenting with the damage numbers and the tracehull variable.

**Comment by Tripperful** [comment]
A variable for changing shotgun spread cone was added, 10 degrees is default value

```
mm_shotgun_spread_angle "10"
```
