### ISSUE TITLE
100 Tick Servers

### ISSUE THREAD

**Issue by Tripperful** [Tripperful/sf-servers-requests#4]
## Server Tick Rate Issues
We found that we had several issues with 200 tick.

- Prop Interactions are worse
- Touching a prop can cause a death more frequently
- Touching a prop can send the player flying
- Client Performance
- Clients with lower end computers struggle to keep up with the 200 tick rate
- Latency is a even more significant issue at 200 tick
‌

### Suggestion
Implement and test out 100 Tick Rate for betters stability

**Comment by da11as911** [comment]
The only issue we have ran into thus far on 100 tick are the prop interactions are still kinda funky and grenade timers may be slightly off, but overall US players seem to enjoy 100 tick better than both 66 and 200.

**Comment by TehEdges** [comment]
@da11as911, I think this can be closed at this point. We've adopted 100 tick without any major issues.

**Comment by da11as911** [comment]
Yes, this can be closed @Tripperful
