### ISSUE TITLE
Add a concommand for versioning

### ISSUE THREAD

**Issue by Tripperful** [Tripperful/sf-servers-requests#6]
There needs to be a console command (something line `sf_version`) which would print a unique build version (an incremental ID, a hash or a guid or some other unique value) to verify game server updates.

**Comment by Tripperful** [comment]
A new command (sv_version) was added which prints the following
![image](https://github.com/Tripperful/sf-servers-requests/assets/28317791/3663258f-f808-475d-979f-c890d128cb65)

**Comment by da11as911** [comment]
Any chance we can get a console command for this? Would be nice to see for people who dont have direct access to the server.
